[package]
name = "libpixiv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
md5 = "0.7.0"
reqwest = "0.12.7"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }

